/* 
CRIE UM BANCO DE DADOS CHAMADO PROJETO E CONECTE-SE A ELE

FALA A MODELAGEM:

Sr JOSE QUER MODERNIZAR SUA OFICINA, E POR ENQUANTO, CADASTRAR OS CARROS
QUE ENTRAM PARA REALIZAR SERVIÇOS E SEUS RESPECTIVOS DONOS.
- Sr JOSE MENCIONOU QUE CADA CLIENTE POSSUI APENAS UM CARRO.
- UM CARRO POSSUI UMA MARCA.
- Sr JOSE QUER SABER AS CORES DOS CARROS PARA TER IDEIA DE QUAL TINTA 
COMPRAR E INFORMA QUE UM CARRO PODE TER MAIS DE UMA COR. 
- Sr JOSE NECESSITA ARMAZENAR OS TELEFONES DOS CLIENTES, MAS NÃO É
OBRIGATÓRIO.
*/ 

CREATE DATABASE SEUJOSE;

USE SEUJOSE;



CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30) NOT NULL,
	SEXO ENUM ('F', 'M') NOT NULL,
	ENDEREÇO VARCHAR (30),
	ID_CARROS INT UNIQUE -- NESSE CASO UNIQUE = 1 CLIENTE SÓ PODE TER 1 CARRO
);



CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('RES', 'CEL', 'COM') NOT NULL,
	NUMERO INT (8) NOT NULL,
	ID_CLIENTE INT -- O MESMO NÚMERO PODE SER DE MAIS DE 1 PESSOA
);



CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR (30) UNIQUE  -- UNIQUE PQ UM CARRO SÓ PODE TER 1 MARCA
);

CREATE TABLE CARROS(
	IDCARROS INT PRIMARY KEY AUTO_INCREMENT,
	PLACA VARCHAR (10) NOT NULL UNIQUE,
	MODELO VARCHAR (30) NOT NULL,
	ANO INT (4) NOT NULL,
	ID_MARCA  INT  -- NÃO COLOCA UNIQUE AQUI PQ OUTROS CARROS PODEM TER A MESMA MARCA
);



CREATE TABLE CORES(
	IDCORES INT PRIMARY KEY AUTO_INCREMENT,
	COR_1 VARCHAR(30) NOT NULL
);


CREATE TABLE CARROS_CORES(
	ID_CARROS INT, 
	ID_CORES INT, 
	PRIMARY KEY (ID_CARROS,ID_CORES)
);


ALTER TABLE TELEFONE 
ADD CONSTRAINT PK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);


ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARROS
FOREIGN KEY(ID_CARROS) 
REFERENCES CARROS(IDCARROS);

ALTER TABLE CARROS 
ADD CONSTRAINT FK_CARROS_MARCA
FOREIGN KEY(ID_MARCA) 
REFERENCES MARCA(IDMARCA);


ALTER TABLE CARROS_CORES
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_CORES)
REFERENCES CORES(IDCORES);

ALTER TABLE CARROS_CORES
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARROS) 
REFERENCES CARROS(IDCARROS);


-- PREENCHER O BANCO COM PELO MENOS 10 CLIENTES

INSERT INTO CARRO VALUES (NULL, '')




