/* STORED PROCEDURES */

BLOCO ANONIMO: Quando a gente faz alguma coisa que n fica salvo no banco: 

SELECT 'NOME' -- Mostra só o nome, mas n ta salvando nada


BLOCO NOMEADO: PROCEDIMENTOS ARMAZENADOS -> PROCEDURES

**TROCAR DELIMITER $ (a programação requer o uso do ;)**

CREATE PROCEDURE NOME ()
BEGIN

	QUALQUER PROGRAMAÇÃO; -- (INSERT, DELETE, UPDATE)

END
$

-- Mostrar o nome da empresa:

CREATE PROCEDURE NOME_EMPRESA()
BEGIN

	SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;

END
$

/* CHAMANDO UMA PROCEDURE */


CALL NOME_EMPRESA()$

DROP PROCEDURE NOME_EMPRESA;  -- APAGA A PROCEDURE


CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT) -- FUNCIONA QUE NEM FUNÇÃO.
BEGIN
	
	SELECT NUMERO1 + NUMERO2 AS CONTA;

END
$

CALL CONTA(100,50)$
CALL CONTA(345634,4354)$
CALL CONTA(55654,56760)$
CALL CONTA(45646,6766)$



DROP DATABASE PROJETO;

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL,'JAVA',30,500.00);
INSERT INTO CURSOS VALUES(NULL,'FUNDAMENTOS DE BANCOS DE DADOS',40,700.00);

DELIMITER #

--PROCEDURE PARA INSERIR INFORMAÇÕES


--							ID CURSO, NOME, HORAS VALOR (N FOI PASSADO O IDCURSO PQ COLOCANOS NO COGIDO COMO NULL PQ ELE N VAI MUDAR)
CREATE PROCEDURE CAD_CURSO (P_NOME VARCHAR(30),
							P_HORAS INT(3),
							P_PRECO FLOAT(10,2) )
BEGIN
	INSERT INTO CURSOS VALUES(NULL,P_NOME, P_HORAS,P_PRECO);

END
#

DELIMITER ;


-- CHAMAR O PROCEDURE COLOCANDO O PARÂMETRO FAZ COM QUE ELE INSIRA OS VALORES DOS PARÂMETROS (JÁ QUE É PRA ISSO QUE ELE SERVE)
CALL CAD_CURSO('BI SQL SERVER', 35, 3.000);
CALL CAD_CURSO('POWER BI', 35, 3.000);
CALL CAD_CURSO('TABLEU', 35, 3.000);

SELECT * FROM CURSOS;

+---------+--------------------------------+-------+--------+
| IDCURSO | NOME                           | HORAS | VALOR  |
+---------+--------------------------------+-------+--------+
|       1 | JAVA                           |    30 | 500.00 |
|       2 | FUNDAMENTOS DE BANCOS DE DADOS |    40 | 700.00 |
|       3 | BI SQL SERVER                  |    35 |   3.00 |
|       4 | POWER BI                       |    35 |   3.00 |
|       5 | TABLEU                         |    35 |   3.00 |
+---------+--------------------------------+-------+--------+


/* CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS */

DELIMITER #


CREATE PROCEDURE P_CONSULTA_CURSOS()
BEGIN
	SELECT * FROM CURSOS;

END
#  -- É isso, funcionou que nem um view.





